spring:
  cloud:
    nacos:
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:adgjl08642}
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:124.221.250.220:8848}
        group: ${NACOS_DISCOVERY_GROUP:DEFAULT_GROUP}
  redis:
    host: ${REDIS_HOST:124.221.250.220}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:adgjl08642}

security:
  gateway-token: ${GATEWAY_TRUST_TOKEN}
