-- Run these queries while the judge load test is active.
-- These are global live-backlog queries. Per-run results are generated by
-- analyze-judge-db.sh and judge-run-summary.sql.
select case status
           when 0 then 'PENDING'
           when 1 then 'SENT'
           when 2 then 'DEAD'
           when 3 then 'DISPATCHING'
           else concat('UNKNOWN_', status)
       end as outbox_status,
       count(*) as total,
       max(retryCount) as max_retry_count
from judge_task_outbox
group by status
order by status;

select case status
           when 0 then 'WAITING'
           when 1 then 'RUNNING'
           when 2 then 'COMPLETED'
           when 3 then 'SYSTEM_FAILED'
           else concat('UNKNOWN_', status)
       end as submission_status,
       count(*) as total,
       round(avg(case when status in (2, 3)
                      then timestampdiff(microsecond, createTime, updateTime)
           end) / 1000, 2) as terminal_avg_end_to_end_ms,
       max(case when status in (2, 3)
                then timestampdiff(second, createTime, updateTime)
           end) as terminal_max_end_to_end_seconds
from question_submit
where isDelete = 0
group by status
order by status;

select count(*) as waiting_over_60_seconds
from question_submit
where status = 0
  and createTime < now() - interval 60 second
  and isDelete = 0;

select count(*) as running_over_180_seconds
from question_submit
where status = 1
  and updateTime < now() - interval 180 second
  and isDelete = 0;
