#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOCAL_ENV_FILE="${SCRIPT_DIR}/local-dev.env"

if [[ ! -f "${SCRIPT_DIR}/.env" ]]; then
  printf 'Missing %s/.env.\n' "${SCRIPT_DIR}" >&2
  exit 1
fi

set -a
# shellcheck disable=SC1091
source "${SCRIPT_DIR}/.env"
set +a

if [[ -z "${SERVER_PUBLIC_IP:-}" || "${SERVER_PUBLIC_IP}" == CHANGE_ME* ]]; then
  printf 'Set SERVER_PUBLIC_IP in %s/.env first.\n' "${SCRIPT_DIR}" >&2
  exit 1
fi

CODESANDBOX_HOST="${LOCAL_CODESANDBOX_HOST:-127.0.0.1}"
NACOS_DISCOVERY_GROUP="${LOCAL_NACOS_DISCOVERY_GROUP:-LOCAL_DEV_GROUP}"

umask 077
cat > "${LOCAL_ENV_FILE}" <<EOF
SPRING_PROFILES_ACTIVE=prod
MYSQL_URL=jdbc:mysql://${SERVER_PUBLIC_IP}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
MYSQL_USERNAME=${MYSQL_USER}
MYSQL_PASSWORD=${MYSQL_PASSWORD}
REDIS_HOST=${SERVER_PUBLIC_IP}
REDIS_PORT=${REDIS_PORT}
REDIS_PASSWORD=${REDIS_PASSWORD}
NACOS_SERVER_ADDR=${SERVER_PUBLIC_IP}:${NACOS_PORT}
NACOS_USERNAME=nacos
NACOS_PASSWORD=${NACOS_ADMIN_PASSWORD}
NACOS_DISCOVERY_GROUP=${NACOS_DISCOVERY_GROUP}
RABBITMQ_HOST=${SERVER_PUBLIC_IP}
RABBITMQ_PORT=${RABBITMQ_PORT}
RABBITMQ_USERNAME=${RABBITMQ_DEFAULT_USER}
RABBITMQ_PASSWORD=${RABBITMQ_DEFAULT_PASS}
MINIO_ENDPOINT=http://${SERVER_PUBLIC_IP}:${MINIO_PORT}
MINIO_PUBLIC_ENDPOINT=http://${SERVER_PUBLIC_IP}:${MINIO_PORT}
MINIO_ACCESS_KEY=${MINIO_ROOT_USER}
MINIO_SECRET_KEY=${MINIO_ROOT_PASSWORD}
MINIO_BUCKET=${MINIO_BUCKET}
CODESANDBOX_URL=http://${CODESANDBOX_HOST}:${CODESANDBOX_PORT}/executeCode
CODESANDBOX_SECRET_KEY=${CODESANDBOX_SECRET_KEY}
CODESANDBOX_TIMESTAMP_TOLERANCE_SECONDS=${CODESANDBOX_TIMESTAMP_TOLERANCE_SECONDS:-300}
LOAD_TEST_CRAWLER_DETECTION_ENABLED=${LOAD_TEST_CRAWLER_DETECTION_ENABLED:-false}
EOF

printf 'Generated local development settings: %s\n' "${LOCAL_ENV_FILE}"
