package com.qwerlty.myojbackendaiservice.authoring.model;

import java.time.LocalDateTime;

public record AuthoringTask(
        long id,
        long userId,
        Long sourceTaskId,
        String idempotencyKey,
        String taskType,
        String requestJson,
        String resultJson,
        AuthoringTaskStatus status,
        AuthoringStage stage,
        int progress,
        int repairCount,
        boolean cancelRequested,
        String errorCode,
        String lastError,
        String modelName,
        String promptVersion,
        String graphVersion,
        String reviewDecision,
        String reviewDraftJson,
        Long reviewerId,
        String reviewComment,
        Long publishedQuestionId,
        LocalDateTime reviewedTime,
        LocalDateTime startedTime,
        LocalDateTime finishedTime,
        LocalDateTime createTime,
        LocalDateTime updateTime
) {
    public AuthoringTask(long id,
                         long userId,
                         Long sourceTaskId,
                         String idempotencyKey,
                         String taskType,
                         String requestJson,
                         String resultJson,
                         AuthoringTaskStatus status,
                         AuthoringStage stage,
                         int progress,
                         int repairCount,
                         boolean cancelRequested,
                         String errorCode,
                         String lastError,
                         String modelName,
                         String promptVersion,
                         String graphVersion,
                         LocalDateTime startedTime,
                         LocalDateTime finishedTime,
                         LocalDateTime createTime,
                         LocalDateTime updateTime) {
        this(id, userId, sourceTaskId, idempotencyKey, taskType, requestJson, resultJson,
                status, stage, progress, repairCount, cancelRequested, errorCode, lastError,
                modelName, promptVersion, graphVersion, null, null, null, null, null, null,
                startedTime, finishedTime, createTime, updateTime);
    }
}
